CREATE TABLE IF NOT EXISTS author
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT author_pk PRIMARY KEY,
    last_name  VARCHAR NOT NULL,
    first_name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS book
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT book_pk PRIMARY KEY,
    title            VARCHAR NOT NULL,
    author_id        BIGINT  NOT NULL
        CONSTRAINT book_author_fk REFERENCES author (id),
    isbn             VARCHAR UNIQUE,
    publication_year INTEGER,
    genre            VARCHAR
);
